name: Semantic OWl API CI nightly run 

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Clippy + rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy, llvm-tools-preview

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1        
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1        
        with:
          command: clippy
          args: -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1        
        run: |
          RUSTFLAGS="-Z instrument-coverage" LLVM_PROFILE_FILE="kng-sem-owl-%m.profraw" cargo test --tests && \
          cargo profdata -- merge -sparse semantic_owl_api/kng-sem-owl-*.profraw -o kng-sem-owl.profdata && \
          cargo profdata -- merge -sparse semantic_owl_cli/kng-sem-owl-*.profraw -o kng-sem-owl.profdata && \
          cargo cov -- report --use-color --instr-profile=kng-sem-owl.profdata && \
          cargo cov -- show --use-color --instr-profile=kng-sem-owl.profdata